### ISSUE TITLE
CSS 修改 body 背景色

### ISSUE THREAD

**Issue by oicoder** [oicoder/blog#4]
[作者：Luwang]: # '<https://cdn.wallleap.cn/img/pic/cover/vue.jpg>'

使用 body 选择器选中然后使用 `background-color` 属性修改

```css
body {
  background-color: gray;
}
```
